language: ruby

rvm:
  - 2.5.5
  - 2.6.3

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile  

cache: bundler

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle